{% set name = "pretrainedmodels" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e77ead4619a3e11ab3c41982c8ad5b86edffe37c87fd2a37ec3c2cc6470b98a

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - munch
    - pytorch
    - torchvision >=0.3.0
    - tqdm
    - scipy

test:
  imports:
    - pretrainedmodels
    - pretrainedmodels.datasets
    - pretrainedmodels.models
    - pretrainedmodels.models.resnext_features

about:
  home: https://github.com/cadene/pretrained-models.pytorch
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  summary: "Pretrained models for Pytorch"
  dev_url: https://github.com/cadene/pretrained-models.pytorch

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - ocefpaf
